version: "3.8"

services:

  part-webserver:
    image: httpd:2.4-alpine
    working_dir: /usr/var/www/
    hostname: part-webserver
    volumes:
      - ./:/usr/var/www/
      - ./devops/docker/apache/vhosts/:/usr/local/apache2/conf/vhosts/
      - ./devops/docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./devops/docker/traefik/certs/:/usr/local/certs/
    depends_on:
      - part-php-fpm
    expose:
      - "443"


  part-php:
    image: 3snetregistry.azurecr.io/tsme/php7.3:xdebug-v4
    working_dir: /usr/var/www
    hostname: part-php-fpm
    volumes:
      - ./:/usr/var/www/
      - ./devops/docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-php.ini
    ports:
      - "8083:443"
      - "8002:80"


  part-filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    working_dir: /usr/var/www
    volumes:
      - ./:/usr/var/www/
    ports:
      - "8083:443"
      - "8002:80"
    profiles:
      - debug

  part-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    working_dir: /usr/var/www
    volumes:
      - ./:/usr/var/www/
    ports:
      - "9200:9200"
      - "9300:9300"
    profiles:
      - debug


  part-kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    working_dir: /usr/var/www
    volumes:
      - ./:/usr/var/www/
    ports:
      - "5601:5601"
    profiles:
      - debug


volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  elk: ~
  backend: ~