version: "3.8"

services:

  httpd:
    image: httpd:2.4-alpine
    working_dir: /usr/var/www/
    hostname: part-webserver
    volumes:
      - ./:/usr/var/www/
      - ./devops/docker/apache/vhosts/:/usr/local/apache2/conf/vhosts/
      - ./devops/docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./devops/docker/traefik/certs/:/usr/local/certs/
    depends_on: [php-fpm]
    ports: ["8083:443", "8002:80"]

  php-fpm:
    image: 3snetregistry.azurecr.io/tsme/php7.3:xdebug-v4
    working_dir: /usr/var/www
    volumes:
      - ./devops/docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./:/usr/var/www/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    depends_on: [httpd]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ["9200:9200", "9300:9300"]
    networks: [log]
    healthcheck:
      test: ["curl", "-X", "GET", "localhost:9200/_cluster/health?pretty"]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_conf:/usr/share/elasticsearch/config/
      - ./devops/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data/
#      - ./devops/docker/elasticsearch/data/:/usr/share/elasticsearch/data/
    profiles: [log]


#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.3.3
#    depends_on: [elasticsearch]
#    ports: ["5601:5601"]
#    profiles: [log]
#
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:8.3.3
#    depends_on: [elasticsearch, httpd, php-fpm]
#    profiles: [log]

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
  elasticsearch_conf:
  elasticsearch_data:

networks:
  log: ~
  backend: ~