version: "3.8"

services:

  part-webserver:
    image: httpd:2.4-alpine
    working_dir: /usr/var/www/
    hostname: part-webserver
    volumes:
      - ./:/usr/var/www/
      - ./devops/docker/apache/vhosts/:/usr/local/apache2/conf/vhosts/
      - ./devops/docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./devops/docker/traefik/certs/:/usr/local/certs/
    depends_on:
      - part-php-fpm
    expose:
      - "443"


  part-php:
    image: 3snetregistry.azurecr.io/tsme/php7.3:xdebug-v4
    working_dir: /usr/var/www
    hostname: part-php-fpm
    volumes:
      - ./:/usr/var/www/
      - ./devops/docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-php.ini
    ports:
      - "8083:443"
      - "8002:80"


volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
