[global]
  sendAnonymousUsage = false
  checkNewVersion = false

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "WARNING"
  #level = "DEBUG"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
#    exposedByDefault = false
    swarmMode = false

  [providers.file]
    filename = "/etc/traefik/traefik_dynamic.toml"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

